[project]
name = "collagrcms"
version = "0.1.0"
description = "Backend service"
readme = "README.md"
requires-python = ">=3.13"

dependencies = [
    "asyncpg>=0.30.0",
    "fastapi>=0.115.12",
    "pillow>=11.2.1",
    "pydantic>=2.11.5",
    "pytest>=8.3.5",
    "python-dotenv>=1.0.0",
    "python-multipart>=0.0.20",
    "pyyml>=0.0.2",
    "sqlalchemy>=2.0.41",
    "uvicorn>=0.34.3",
]

[tool.setuptools.packages]
packages = ["src"]


[tool.ruff]
preview = true
line-length = 88

[tool.ruff.lint]
select = ["E", "F", "B"]
ignore = ["E501"]


