name: Python Test Only

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: archlinux:latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        pacman -S uv --noconfirm
        uv sync 

    - name: Run tests and save log
      run: |
        set -o pipefail
        uv run tests/core/test_image_collage.py 2>&1 | tee test-log.txt

    - name: Upload test log
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: test-log
        path: test-log.txt
